name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# jobs:
#   build:
#     runs-on: ${{matrix.os}}
#     strategy:
#       matrix:
#        os: [ubuntu-latest, windows-latest,macOS-latest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: "1.8"
          
    - name: Grant the Gradle permission 
      run: chmod +x gradlew
  
    - name: Build with Gradle 
      run: ./gradlew build
      
    - name: list the files 
      run: cd build/libs/ && ls -ltrh

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: mbchandashah/docker-repository
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

